/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnexRouteImport } from './routes/anex'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as PontosRouteImport } from './routes/pontos'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as EncomendaIdRouteImport } from './routes/encomenda.$id'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ReferenciaIdRouteImport } from './routes/referencia.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnexRoute = AnexRouteImport.update({
  id: '/anex',
  path: '/anex',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const PontosRoute = PontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EncomendaIdRoute = EncomendaIdRouteImport.update({
  id: '/encomenda/$id',
  path: '/encomenda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciaIdRoute = ReferenciaIdRouteImport.update({
  id: '/referencia/$id',
  path: '/referencia/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anex': typeof AnexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/checkout': typeof CheckoutRoute
  '/legal': typeof LegalRoute
  '/marcas': typeof MarcasRoute
  '/packs': typeof PacksRoute
  '/pontos': typeof PontosRoute
  '/shop': typeof ShopRoute
  '/conta': typeof AuthenticatedContaRoute
  '/encomenda/$id': typeof EncomendaIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/referencia/$id': typeof ReferenciaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anex': typeof AnexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/checkout': typeof CheckoutRoute
  '/legal': typeof LegalRoute
  '/marcas': typeof MarcasRoute
  '/packs': typeof PacksRoute
  '/pontos': typeof PontosRoute
  '/shop': typeof ShopRoute
  '/conta': typeof AuthenticatedContaRoute
  '/encomenda/$id': typeof EncomendaIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/referencia/$id': typeof ReferenciaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/anex': typeof AnexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/checkout': typeof CheckoutRoute
  '/legal': typeof LegalRoute
  '/marcas': typeof MarcasRoute
  '/packs': typeof PacksRoute
  '/pontos': typeof PontosRoute
  '/shop': typeof ShopRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/encomenda/$id': typeof EncomendaIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/referencia/$id': typeof ReferenciaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anex'
    | '/auth'
    | '/b2b'
    | '/checkout'
    | '/legal'
    | '/marcas'
    | '/packs'
    | '/pontos'
    | '/shop'
    | '/conta'
    | '/encomenda/$id'
    | '/product/$handle'
    | '/referencia/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anex'
    | '/auth'
    | '/b2b'
    | '/checkout'
    | '/legal'
    | '/marcas'
    | '/packs'
    | '/pontos'
    | '/shop'
    | '/conta'
    | '/encomenda/$id'
    | '/product/$handle'
    | '/referencia/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anex'
    | '/auth'
    | '/b2b'
    | '/checkout'
    | '/legal'
    | '/marcas'
    | '/packs'
    | '/pontos'
    | '/shop'
    | '/_authenticated/conta'
    | '/encomenda/$id'
    | '/product/$handle'
    | '/referencia/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnexRoute: typeof AnexRoute
  AuthRoute: typeof AuthRoute
  B2bRoute: typeof B2bRoute
  CheckoutRoute: typeof CheckoutRoute
  LegalRoute: typeof LegalRoute
  MarcasRoute: typeof MarcasRoute
  PacksRoute: typeof PacksRoute
  PontosRoute: typeof PontosRoute
  ShopRoute: typeof ShopRoute
  EncomendaIdRoute: typeof EncomendaIdRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ReferenciaIdRoute: typeof ReferenciaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anex': {
      id: '/anex'
      path: '/anex'
      fullPath: '/anex'
      preLoaderRoute: typeof AnexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontos': {
      id: '/pontos'
      path: '/pontos'
      fullPath: '/pontos'
      preLoaderRoute: typeof PontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/encomenda/$id': {
      id: '/encomenda/$id'
      path: '/encomenda/$id'
      fullPath: '/encomenda/$id'
      preLoaderRoute: typeof EncomendaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencia/$id': {
      id: '/referencia/$id'
      path: '/referencia/$id'
      fullPath: '/referencia/$id'
      preLoaderRoute: typeof ReferenciaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnexRoute: AnexRoute,
  AuthRoute: AuthRoute,
  B2bRoute: B2bRoute,
  CheckoutRoute: CheckoutRoute,
  LegalRoute: LegalRoute,
  MarcasRoute: MarcasRoute,
  PacksRoute: PacksRoute,
  PontosRoute: PontosRoute,
  ShopRoute: ShopRoute,
  EncomendaIdRoute: EncomendaIdRoute,
  ProductHandleRoute: ProductHandleRoute,
  ReferenciaIdRoute: ReferenciaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
